name: sim_multiple_uwb
root: ./
startup_window: kalman_filter 
pre_window: export RUN_TYPE=simulation; export UAV_TYPE=x500; export WORLD_NAME=simulation; export ODOMETRY_TYPE=gps; export SENSORS="garmin_down"
windows:
  - kalman_filter:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav29; waitForControl; roslaunch uvdar_core uvdar_kalman.launch output_frame:=$UAV_NAME/stable_origin
        - export UAV_NAME=uav30; waitForControl; roslaunch uvdar_core uvdar_kalman.launch output_frame:=$UAV_NAME/stable_origin
        - export UAV_NAME=uav38; waitForControl; roslaunch uvdar_core uvdar_kalman.launch output_frame:=$UAV_NAME/stable_origin
  - object_tracker_simple:
      layout: tilted #even-vertical
      panes:
        - export UAV_NAME=uav29; waitForControl; history -s roslaunch object_tracker tracker_multiple_UWB.launch distance_frame:=$UAV_NAME/fcu kalman_frame:=$UAV_NAME/stable_origin output_frame:=$UAV_NAME/stable_origin
        - export UAV_NAME=uav30; waitForControl; history -s roslaunch object_tracker tracker_multiple_UWB.launch distance_frame:=$UAV_NAME/fcu kalman_frame:=$UAV_NAME/stable_origin output_frame:=$UAV_NAME/stable_origin
        - export UAV_NAME=uav38; waitForControl; history -s roslaunch object_tracker tracker_multiple_UWB.launch distance_frame:=$UAV_NAME/fcu kalman_frame:=$UAV_NAME/stable_origin output_frame:=$UAV_NAME/stable_origin
  - uwb_range_uwb_lnn:
      layout: tilted #even-vertical
      panes:
        - export UAV_NAME=uav29; waitForControl; roslaunch uwb_range_fake uwb_lnn.launch output_id:=3 target_uav:=uav30 output_frame:=$UAV_NAME/fcu
        - export UAV_NAME=uav30; waitForControl; roslaunch uwb_range_fake uwb_lnn.launch output_id:=2 target_uav:=uav29 output_frame:=$UAV_NAME/fcu
        - export UAV_NAME=uav38; waitForControl; roslaunch uwb_range_fake uwb_lnn.launch output_id:=3 target_uav:=uav30 output_frame:=$UAV_NAME/fcu
        - export UAV_NAME=uav30; waitForControl; roslaunch uwb_range_fake uwb_lnn.launch output_id:=4 target_uav:=uav38 output_frame:=$UAV_NAME/fcu
        - export UAV_NAME=uav29; waitForControl; roslaunch uwb_range_fake uwb_lnn.launch output_id:=4 target_uav:=uav38 output_frame:=$UAV_NAME/fcu
        - export UAV_NAME=uav38; waitForControl; roslaunch uwb_range_fake uwb_lnn.launch output_id:=2 target_uav:=uav29 output_frame:=$UAV_NAME/fcu
  - uvdar_measured_poses_29:
        layout: even-horizontal
        synchronize: after
        panes:
          - 'history -s rostopic echo /uav29/uvdar/measuredPosesL'
          - 'history -s rostopic echo /uav29/uvdar/measuredPosesR'
  - uvdar_measured_poses_30:
        layout: even-horizontal
        synchronize: after
        panes:
          - 'history -s rostopic echo /uav30/uvdar/measuredPosesL'
          - 'history -s rostopic echo /uav30/uvdar/measuredPosesR'
  - uwb_range:
        layout: even-horizontal
        synchronize: after
        panes:
          - 'history -s rostopic echo /uav29/uwb_range_uav30/range'
          - 'history -s rostopic echo /uav30/uwb_range_uav29/range'
          - 'history -s rostopic echo /uav29/uwb_range_uav38/range'
          - 'history -s rostopic echo /uav38/uwb_range_uav29/range'
  - object_tracker_simple_echo:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav29; waitForControl; history -s rostopic echo /$UAV_NAME/object_tracker/filtered_poses
        - export UAV_NAME=uav30; waitForControl; history -s rostopic echo /$UAV_NAME/object_tracker/filtered_poses
        - export UAV_NAME=uav38; waitForControl; history -s rostopic echo /$UAV_NAME/object_tracker/filtered_poses
  - object_tracker_simple_echo:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav29; waitForControl; history -s rostopic echo /$UAV_NAME/object_tracker/object_tracker/poses
        - export UAV_NAME=uav30; waitForControl; history -s rostopic echo /$UAV_NAME/object_tracker/object_tracker/poses
        - export UAV_NAME=uav38; waitForControl; history -s rostopic echo /$UAV_NAME/object_tracker/object_tracker/poses
  - object_tracker_simple_echo:
      layout: even-vertical
      panes:
        - export UAV_NAME=uav29; waitForControl; history -s rostopic hz /$UAV_NAME/object_tracker/object_tracker/poses
        - export UAV_NAME=uav30; waitForControl; history -s rostopic hz /$UAV_NAME/object_tracker/object_tracker/poses
        - export UAV_NAME=uav38; waitForControl; history -s rostopic hz /$UAV_NAME/object_tracker/object_tracker/poses
  

  
